Improve Mapping Code Quality
ehrbase/fhir-bridge pull request #106
Opened 2020-11-23 13:43 UTC by jsachau

Improve Mapping Code Quality

2020-11-23 15:21 UTC, jsachau commented on src/main/java/org/ehrbase/fhirbridge/mapping/FhirObservationPatientAufICUOpenehrPatientAufICU.java
> +        if (coding.getSystem().equals("http://snomed.info/sct")) {
The code can be null, i.e. if the observation uses a SNOMED code which was not yet covered by the template. `ofNullable` should cover this case because according to the [docs](https://docs.oracle.com/javase/8/docs/api/java/util/Optional.html) it should return an empty `Optional` if the value is not present in the map. We can also shorten the whole query to a single if statement, but the template will be extended with new codes of different systems in the near future.

2020-11-23 15:49 UTC, SevKohler commented on src/main/java/org/ehrbase/fhirbridge/mapping/FhirObservationPatientAufICUOpenehrPatientAufICU.java
> +    static {
When deleting static this also has to be refactored.

2020-11-23 15:49 UTC, SevKohler commented on src/main/java/org/ehrbase/fhirbridge/mapping/FhirObservationPatientAufICUOpenehrPatientAufICU.java
> +        if (coding.getSystem().equals("http://snomed.info/sct")) {
If it can be ofNullable, and you want to catch this case explicitly make it so. It is up to you if the code will be extended in the near future.

2020-11-24 11:35 UTC, jsachau commented on src/main/java/org/ehrbase/fhirbridge/mapping/FhirObservationPatientAufICUOpenehrPatientAufICU.java
> +    public static PatientAufICUComposition map(Observation fhirObservation) {
The reason why this method is static, is that we agreed on this standard for the mapping classes a few month ago when the project started. I think in cases like this, removing the static would be the better option. However, I think we should remove the static for all mapping classes instead of having some which use a static map function and others which don't. We should open a separate ticket for this.

2020-11-24 11:35 UTC, jsachau commented on src/main/java/org/ehrbase/fhirbridge/mapping/FhirObservationPatientAufICUOpenehrPatientAufICU.java
> +    static {
see below.

2020-11-24 11:38 UTC, jsachau commented
@SevKohler I shortened the map function again. The rest of the code issues, i.e. the removal of the `static` keyword should be handled in a different issue where the mapping class standard is changed for all mappings.

2020-11-24 12:05 UTC, SevKohler requested changes

2020-11-24 12:05 UTC, SevKohler commented on src/main/java/org/ehrbase/fhirbridge/mapping/FhirObservationPatientAufICUOpenehrPatientAufICU.java
> +    public static PatientAufICUComposition map(Observation fhirObservation) {
This needs to be refactored (ifs should be in separate method).

2020-11-24 12:16 UTC, jsachau commented on src/main/java/org/ehrbase/fhirbridge/mapping/FhirObservationPatientAufICUOpenehrPatientAufICU.java
> +        if (coding.getSystem().equals("http://snomed.info/sct")) {
Switched to a single if. We will add the `Optional` once it is needed

2020-11-24 12:47 UTC, SevKohler approved these changes

2020-11-24 13:00 UTC, merged