Feature/02_mapping_blood_pressure
ehrbase/fhir-bridge pull request #15
Opened 2020-09-06 16:39 UTC by jsachau

Created the mapping and the associated unit tests. 

I'm not sure if the mapping _FHIR Observation bodySite --> strukturierteStelleDerMessung_ is necessary as I can not see how appropriately convert the FHIR _Coding_ datatype to a OpenEHR _Cluster_ datatype.

Note: The subject of the composition is automatically set to `new PartySelf()` and not to the subject of the composition.

2020-09-15 20:33 UTC, ppazos commented
@jsachau please merge with develop to solve conflicts and the test errors in the CI https://app.circleci.com/pipelines/github/ehrbase/fhir-bridge/51/workflows/a409c6a6-78d8-48bb-9649-0999ca7dee40/jobs/51

2020-09-16 10:44 UTC, jsachau commented
@ppazos I have merged the newest develop branch but the two tests still fail. Are you aware that the `FhirBridgeApplicationIT` class has been renamed again?

2020-09-16 15:10 UTC, ppazos commented
@jsachau yes, it was renamed back by our devops. Let me check your branch, in general we can't merge if there are failing tests.

2020-09-17 01:24 UTC, ppazos requested changes

2020-09-17 01:24 UTC, ppazos commented on src/test/java/org/ehrbase/fhirbridge/FhirBridgeApplicationIT.java
> +        Assertions.assertEquals(
@jsachau after testing I understood the issue now: the problem is you added a profile, so the message of this exception changed: you need to add your profile to the assertEquals text, you can check the right value in the exception you are getting with $ mvn clean install, it says: the value is xxxx and yyy was expected.

2020-09-17 01:24 UTC, ppazos commented on src/test/java/org/ehrbase/fhirbridge/FhirBridgeApplicationIT.java
> +        Assertions.assertEquals(
@jsachau the same happens with this test, it fails because the text was not updated.

Please check the CI https://app.circleci.com/pipelines/github/ehrbase/fhir-bridge/79/workflows/04820950-f867-4a25-85e8-4f680acf14d1/jobs/79

Or the output of the errors when running $ mvn clean install

2020-09-17 19:43 UTC, merged