Feature/06 mapping heart rate
ehrbase/fhir-bridge pull request #24
Opened 2020-09-15 11:43 UTC by ErikTute

Implemented mapping, merged with current develop, creating composition still works, don't know what else to describe its my first review ;-)

2020-09-15 20:34 UTC, ppazos commented
@ErikTute please fix the error in the code reported by the CI https://app.circleci.com/pipelines/github/ehrbase/fhir-bridge/68/workflows/87eaaee0-bf31-46ac-af08-1006f35547f6/jobs/68

2020-09-16 07:58 UTC, ErikTute commented
I fixed the initial error. But now there is an other error that seems to be related to a test I have nothing to do with... @ppazos any recommendations how to deal with that? I get the same error also in the fio2 mapping, so your answer will be valuable twice ;-)

2020-09-16 15:12 UTC, ppazos commented
Thanks @ErikTute can you please test the current develop to see if that test fails in your machine? It might be an issue in the develop branch. @jsachau is also having failing tests on her branch.

2020-09-17 01:20 UTC, ppazos requested changes

2020-09-17 01:20 UTC, ppazos commented on src/main/java/org/ehrbase/fhirbridge/rest/EhrbaseService.java
> +        {
@ErikTute please fix indentation

2020-09-17 01:20 UTC, ppazos commented on src/test/java/org/ehrbase/fhirbridge/FhirBridgeApplicationIT.java
> +                /*UnprocessableEntityException exception = Assertions.assertThrows(UnprocessableEntityException.class,
@ErikTute this test should run.

2020-09-17 01:20 UTC, ppazos commented on src/test/java/org/ehrbase/fhirbridge/FhirBridgeApplicationIT.java
> +                /*UnprocessableEntityException exception = Assertions.assertThrows(UnprocessableEntityException.class,
@ErikTute this test should run

2020-09-17 01:22 UTC, ppazos commented
@ErikTute After testing I understood the issue now: the problem is you added a profile, so the message of this exception changed: you need to add your profile to the assertEquals text, you can check the right value in the exception you are getting with $ mvn clean install, it says: the value is xxxx and yyy was expected.

You need to update the createObservationUsingDefaultProfile() test, and all the tests that might fail that are now returning the profile you added so they pass.

This is the same that happened to @jsachau on her PR https://github.com/ehrbase/fhir-bridge/pull/15/files#diff-11fd6d80577350c58b9616fb5f15b644R291

2020-09-17 07:39 UTC, ErikTute commented
Hi @ppazos, thanks for your help so far. We just had our daily with Birger, he proposed, that since I have just 20% of my position on this project, to get this issue finished, that I kindly ask you to finalize the heart rate and fio2 mapping. Kind regards

2020-09-17 18:58 UTC, merged