Feature/50 mapping pregnancy status
ehrbase/fhir-bridge pull request #31
Opened 2020-09-25 01:03 UTC by ppazos

Added mapping for pregnancy status create. There is one issue that needs to be solved to add the last mapping: https://github.com/ehrbase/openEHR_SDK/issues/84

For https://github.com/ehrbase/num_platform/issues/50

2020-10-04 21:08 UTC, birgerhaarbrandt requested changes
Please carefully check the code for any remains of the lab values...

2020-10-04 21:08 UTC, birgerhaarbrandt commented on src/main/java/org/ehrbase/fhirbridge/mapping/FhirObservationPregnancyStatusOpenehrPregnancyStatus.java
> +    /**
What's the purpose of this commented section?

2020-10-04 21:08 UTC, birgerhaarbrandt commented on src/main/java/org/ehrbase/fhirbridge/mapping/FhirObservationPregnancyStatusOpenehrPregnancyStatus.java
> +            case "LA26683-5": // not pregmant
typo

2020-10-04 21:08 UTC, birgerhaarbrandt commented on src/main/java/org/ehrbase/fhirbridge/mapping/FhirObservationPregnancyStatusOpenehrPregnancyStatus.java
> +        composition.setSettingDefiningcode(SettingDefiningcode.EMERGENCY_CARE);
mark as //fixme

2020-10-04 21:08 UTC, birgerhaarbrandt commented on src/main/java/org/ehrbase/fhirbridge/mapping/FhirObservationPregnancyStatusOpenehrPregnancyStatus.java
> +        composition.setSettingDefiningcode(SettingDefiningcode.EMERGENCY_CARE);
SECONDARY_CARE instead of EMERGENCY_CARE

2020-10-04 21:08 UTC, birgerhaarbrandt commented on src/main/java/org/ehrbase/fhirbridge/mapping/FhirObservationPregnancyStatusOpenehrPregnancyStatus.java
> +     * this maps a single lab observation to a composition, the map(DiagnosticReport) method maps a
Please remove this copy & paste stuff

2020-10-04 21:08 UTC, birgerhaarbrandt commented on src/main/java/org/ehrbase/fhirbridge/mapping/FhirObservationPregnancyStatusOpenehrPregnancyStatus.java
> + * FHIR to openEHR - Laboratory report
Remove copy & paste error

2020-10-07 00:56 UTC, ppazos commented on src/main/java/org/ehrbase/fhirbridge/mapping/FhirObservationPregnancyStatusOpenehrPregnancyStatus.java
> +        composition.setSettingDefiningcode(SettingDefiningcode.EMERGENCY_CARE);
@birgerhaarbrandt These are the codes currently available. We were using emergency as a placeholder since there is no criteria on that field's value. I think that should be defined for each mapping.

  SECONDARY_ALLIED_HEALTH_CARE("secondary allied health care", "secondary allied health care", "openehr", "234"),

  SECONDARY_NURSING_CARE("secondary nursing care", "secondary nursing care", "openehr", "233"),

  EMERGENCY_CARE("emergency care", "emergency care", "openehr", "227"),

  PRIMARY_NURSING_CARE("primary nursing care", "primary nursing care", "openehr", "229"),

  PRIMARY_ALLIED_HEALTH_CARE("primary allied health care", "primary allied health care", "openehr", "230"),

  COMPLEMENTARY_HEALTH_CARE("complementary health care", "complementary health care", "openehr", "235"),

  MIDWIFERY_CARE("midwifery care", "midwifery care", "openehr", "231"),

  PRIMARY_MEDICAL_CARE("primary medical care", "primary medical care", "openehr", "228"),

  SECONDARY_MEDICAL_CARE("secondary medical care", "secondary medical care", "openehr", "232"),

  NURSING_HOME_CARE("nursing home care", "nursing home care", "openehr", "237"),

  DENTAL_CARE("dental care", "dental care", "openehr", "236"),

  HOME("home", "home", "openehr", "225"),

  OTHER_CARE("other care", "other care", "openehr", "238");

2020-10-27 21:39 UTC, merged