Feature/370 support persistence
ehrbase/fhir-bridge pull request #32
Opened 2020-09-28 06:01 UTC by subigre

Pull request regarding ehrbase/project_management#370

2020-09-29 18:51 UTC, ppazos requested changes
@subigre see small changes requested.

2020-09-29 18:51 UTC, ppazos commented on src/test/resources/Observation/observation-bloodpressure-example.json
> +    "reference": "urn:uuid:example"
@subigre please set a UUID like 07f602e0-579e-4fe3-95af-381728bf0d49 to "example"

2020-09-29 18:51 UTC, ppazos commented on src/test/java/org/ehrbase/fhirbridge/FhirBridgeApplicationIT.java
> +        resource = resource.replaceAll("urn:uuid:example", "urn:uuid:" + this.subjectIdValue);
@subigre please change the "example" matching to the uuid format matching to keep all the tests similar.

2020-09-29 18:51 UTC, ppazos commented on src/test/java/org/ehrbase/fhirbridge/FhirBridgeApplicationIT.java
> +                "urn:uuid:([0-9a-fA-F]{8}\\-[0-9a-fA-F]{4}\\-[0-9a-fA-F]{4}\\-[0-9a-fA-F]{4}\\-[0-9a-fA-F]{12})",
@subigre please bring indentation back 4 spaces (same for the tests below)

2020-09-29 18:52 UTC, ppazos commented
@subigre please also check the conflict with develop branch.

2020-09-29 20:24 UTC, subigre commented
Dear @ppazos, I did the requested changes

2020-09-30 17:07 UTC, ppazos approved these changes
Looks good :shipit:

2020-09-30 17:10 UTC, merged