mapping done
ehrbase/fhir-bridge pull request #51
Opened 2020-10-14 18:49 UTC by MDSchulze

Fixes ehrbase/num_platform_issues/45

2020-10-16 17:21 UTC, ppazos requested changes
@MDSchulze please update the tests to pass https://app.circleci.com/pipelines/github/ehrbase/fhir-bridge/218/workflows/95835254-3ff6-4728-90f9-6cf2853fc865/jobs/222

2020-10-16 17:21 UTC, ppazos commented on src/main/java/org/ehrbase/fhirbridge/fhir/provider/ObservationResourceProvider.java
> +            auditService.registerMapResourceEvent(AuditEvent.AuditEventOutcome._0, "Success", observation);
@MDSchulze please fix indentation

2020-10-16 17:21 UTC, ppazos commented on src/main/java/org/ehrbase/fhirbridge/mapping/FHIRObservationBodyWeightOpenehrBodyWeight.java
> +    	KorpergewichtComposition composition = new KorpergewichtComposition();
@MDSchulze please fix indentation

2020-10-27 21:54 UTC, ppazos commented
@MDSchulze can you please check the conflicts with develop branch and update the tests that are not passing?

2020-11-10 16:08 UTC, ppazos commented
@SevKohler @MDSchulze I'm trying to test but getting:

`Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'observationResourceProvider' defined in URL [jar:file:/home/pab/GitHub/fhir-bridge/target/fhir-bridge-1.0.0-SNAPSHOT.jar!/org/ehrbase/fhirbridge/fhir/provider/ObservationResourceProvider.class]: Unsatisfied dependency expressed through constructor parameter 2; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'auditService' defined in URL [jar:file:/home/pab/GitHub/fhir-bridge/target/fhir-bridge-1.0.0-SNAPSHOT.jar!....`

Should I update something to get the SNAPSHOT dependency? Maybe @wlad knows about this?

2020-11-11 16:04 UTC, ppazos commented
The issue above was because of a DB misconfiguration, now solved and the tests are passing.

2020-11-11 16:04 UTC, ppazos approved these changes
+1

2020-11-11 16:05 UTC, merged

2020-11-12 09:50 UTC, birgerhaarbrandt commented
@ppazos please re-review with high priority, we need this by tomorrow