Feature/43 mapping frailty scala
ehrbase/fhir-bridge pull request #55
Opened 2020-10-16 14:53 UTC by BirgitSaalfeld

Dear @ppazos Pablo,
I finished the mapping and merged the develop branch. For some reason I don't know it runs perfectly in terminal, but fails totally in IntelliJ. 

Please review my changes. 

Thanks a lot,
Birgit

2020-10-21 08:05 UTC, BirgitSaalfeld commented
It runs in IntelliJ now :) Have no clue why it changed the behaviour.

2020-10-27 21:52 UTC, ppazos commented
@BirgitSaalfeld can you please check the conflicts with develop branch?

2020-10-28 13:53 UTC, BirgitSaalfeld commented
@ppazos Now the branch ist up to date with the current develop branch

-

2020-10-28 16:15 UTC, ppazos requested changes

2020-10-28 16:15 UTC, ppazos commented on src/test/java/org/ehrbase/fhirbridge/FhirBridgeApplicationIT.java
> +                "Default profile is not supported for Observation. One of the following profiles is expected: " +
@BirgitSaalfeld please fix the indentation to 4 spaces.

2020-10-28 16:15 UTC, ppazos commented on src/test/java/org/ehrbase/fhirbridge/FhirBridgeApplicationIT.java
> +                "Profile http://hl7.org/fhir/StructureDefinition/vitalsigns is not supported for Observation. " +
@BirgitSaalfeld please fix the indentation to 4 spaces.

2020-10-30 16:50 UTC, ppazos requested changes
@BirgitSaalfeld please check the comments about indentation.

2020-11-04 09:38 UTC, BirgitSaalfeld commented on src/test/java/org/ehrbase/fhirbridge/FhirBridgeApplicationIT.java
> +                "Profile http://hl7.org/fhir/StructureDefinition/vitalsigns is not supported for Observation. " +
done

2020-11-04 09:40 UTC, BirgitSaalfeld commented
Dear @ppazos 
I adapted the indentation. Thank you for the detailed explanation. There is still the red circle "changed requested", though I clicked "resolved"-button after your change request. Do I have to do more?

2020-11-04 18:43 UTC, ppazos approved these changes

2020-11-04 18:43 UTC, merged