Feature/72 mapping patient in icu
ehrbase/fhir-bridge pull request #57
Opened 2020-10-19 08:57 UTC by jsachau

Finished Patient in ICU Mapping. This fixes issue [#72](https://github.com/ehrbase/num_platform/issues/72).

2020-10-27 21:55 UTC, ppazos commented
@jsachau  can you please check the conflicts with develop branch?

2020-10-29 09:05 UTC, jsachau commented
@ppazos I have merged the newest develop branch

2020-10-30 16:53 UTC, ppazos requested changes

2020-10-30 16:53 UTC, ppazos commented on src/test/java/org/ehrbase/fhirbridge/FhirBridgeApplicationIT.java
> +                "Default profile is not supported for Observation. One of the following profiles is expected: [http://hl7.org/fhir/StructureDefinition/bodytemp, https://www.netzwerk-universitaetsmedi
@jsachau can you please use the multiline layout? it is easier to read.

2020-10-30 16:53 UTC, ppazos commented on src/test/java/org/ehrbase/fhirbridge/FhirBridgeApplicationIT.java
> +                "Profile http://hl7.org/fhir/StructureDefinition/vitalsigns is not supported for Observation. One of the following profiles is expected: [http://hl7.org/fhir/StructureDefinition/bodyt
@jsachau can you please use the multiline layout? it is easier to read.

2020-10-30 18:11 UTC, jsachau commented on src/test/java/org/ehrbase/fhirbridge/FhirBridgeApplicationIT.java
> +                "Default profile is not supported for Observation. One of the following profiles is expected: [http://hl7.org/fhir/StructureDefinition/bodytemp, https://www.netzwerk-universitaetsmedi
@ppazos yes i did.

2020-10-30 18:12 UTC, jsachau commented on src/test/java/org/ehrbase/fhirbridge/FhirBridgeApplicationIT.java
> +                "Profile http://hl7.org/fhir/StructureDefinition/vitalsigns is not supported for Observation. One of the following profiles is expected: [http://hl7.org/fhir/StructureDefinition/bodyt
@ppazos there too. Sorry!

2020-11-04 15:12 UTC, jsachau commented
@ppazos I have updated the code a few days ago. The requested change is outdated since then.

2020-11-04 16:08 UTC, ppazos approved these changes

2020-11-04 16:09 UTC, merged