Feature/iss10 body height2
ehrbase/fhir-bridge pull request #65
Opened 2020-10-21 07:54 UTC by BirgitSaalfeld

Dear Pablo, 
please check my mapping of the body height.

Regards,
Birgit

2020-10-27 21:53 UTC, ppazos commented
@BirgitSaalfeld can you please check the conflicts with develop branch?

2020-10-28 14:15 UTC, BirgitSaalfeld commented
Dear @ppazos, I reintegrated the current develop branch.

2020-10-28 16:16 UTC, ppazos requested changes

2020-10-28 16:16 UTC, ppazos commented on src/test/java/org/ehrbase/fhirbridge/FhirBridgeApplicationIT.java
> +                "Default profile is not supported for Observation. One of the following profiles is expected: " +
@BirgitSaalfeld please fix the indentation to 4 spaces.

2020-10-28 16:16 UTC, ppazos commented on src/test/java/org/ehrbase/fhirbridge/FhirBridgeApplicationIT.java
> +                "Profile http://hl7.org/fhir/StructureDefinition/vitalsigns is not supported for Observation. " +
@BirgitSaalfeld please fix the indentation to 4 spaces.

2020-10-28 16:28 UTC, BirgitSaalfeld commented on src/test/java/org/ehrbase/fhirbridge/FhirBridgeApplicationIT.java
> +                "Profile http://hl7.org/fhir/StructureDefinition/vitalsigns is not supported for Observation. " +
Four spaces counted from what? I learned programming guidlines like this. Do we have guidlines in this project or is there an auto-formatting we can use?

2020-11-03 22:10 UTC, ppazos commented on src/test/java/org/ehrbase/fhirbridge/FhirBridgeApplicationIT.java
> +                "Profile http://hl7.org/fhir/StructureDefinition/vitalsigns is not supported for Observation. " +
Hi @BirgitSaalfeld please check the 'green' vs. 'red', the red code is 4 spaces to the right from the container line 'Assertions.assertEquals(' while the green is 8 spaces to the right from that.

2020-11-03 22:11 UTC, ppazos commented on src/test/java/org/ehrbase/fhirbridge/FhirBridgeApplicationIT.java
> +                "Profile http://hl7.org/fhir/StructureDefinition/vitalsigns is not supported for Observation. " +
BTW for the format I think we use the SonarLint plugin

- https://www.sonarlint.org/vscode
- https://www.sonarlint.org/intellij

2020-11-04 09:41 UTC, BirgitSaalfeld commented on src/test/java/org/ehrbase/fhirbridge/FhirBridgeApplicationIT.java
> +                "Default profile is not supported for Observation. One of the following profiles is expected: " +
adapted indentation

2020-11-04 09:41 UTC, BirgitSaalfeld commented on src/test/java/org/ehrbase/fhirbridge/FhirBridgeApplicationIT.java
> +                "Profile http://hl7.org/fhir/StructureDefinition/vitalsigns is not supported for Observation. " +
done

2020-11-04 09:42 UTC, BirgitSaalfeld commented
same queston as in the other pull request.

2020-11-04 17:34 UTC, ppazos approved these changes

2020-11-04 17:35 UTC, merged